### ISSUE TITLE
/config/custom_components/wyzeapi/switch.py errors

### ISSUE THREAD

**Issue by Ace0510** [SecKatie/ha-wyzeapi#488]
**Describe the bug**
Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: June 30, 2023 at 12:29:35 PM **(1738 occurrences)**
Last logged: 4:14:42 PM

Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-GW_GC2_D03F2777F7D7': (<Device: DeviceTypes.CAMERA, GW_GC2_D03F2777F7D7>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 455, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in state if (is_on := self.is_on) is None: ^^^^^^^^^^ File "/config/custom_components/wyzeapi/switch.py", line 444, in is_on return self._device.motion ^^^^^^^^^^^^^^^^^^^ AttributeError: 'Camera' object has no attribute 'motion'

```

**Comment by Ace0510** [comment]
I am running: 
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
