### ISSUE TITLE
[Bug] AttributeError: 'Camera' object has no attribute 'motion' - On Wyze CAM OG

### ISSUE THREAD

**Issue by dinan5** [SecKatie/ha-wyzeapi#496]
**Describe the bug**
I installed two Wyze Cam OG cameras, restarted HA and these cameras throw the follow error:
AttributeError: 'Camera' object has no attribute 'motion'
2023-07-26 09:47:59.171 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-GW_GC1_D03F277F46F0': (<Device: DeviceTypes.CAMERA, GW_GC1_D03F277F46F0>,)
Traceback (most recent call last):
File "/config/custom_components/wyzeapi/switch.py", line 455, in handle_camera_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in state
if (is_on := self.is_on) is None:
^^^^^^^^^^
File "/config/custom_components/wyzeapi/switch.py", line 444, in is_on
return self._device.motion

**To Reproduce**

1. Install OG camera
2. Restart HA

**Expected behavior**
Normal camera activation

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
AttributeError: 'Camera' object has no attribute 'motion'
2023-07-26 09:47:59.171 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-GW_GC1_D03F277F46F0': (<Device: DeviceTypes.CAMERA, GW_GC1_D03F277F46F0>,)
Traceback (most recent call last):
File "/config/custom_components/wyzeapi/switch.py", line 455, in handle_camera_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in state
if (is_on := self.is_on) is None:
^^^^^^^^^^
File "/config/custom_components/wyzeapi/switch.py", line 444, in is_on
return self._device.motion

```

**Comment by brg468** [comment]
Probably a duplicate of https://github.com/SecKatie/ha-wyzeapi/issues/488. 

I’m guessing the OG cams don’t support motion detection so they need to be excluded like the doorbell cams are. Can you tell me the model number of the camera from the device info in HA?

**Comment by dinan5** [comment]
> Probably a duplicate of #488.
> 
> I’m guessing the OG cams don’t support motion detection so they need to be excluded like the doorbell cams are. Can you tell me the model number of the camera from the device info in HA?

GW_CG1. it supports motion detection

**Comment by dinan5** [comment]
If there is any log / debug data I can provide, I'm happy to collaborate.

**Comment by brg468** [comment]
I was going to look into sharing your cam with my account, but until the auth issue gets resolved I can’t even log into my dev account to try anything. Hopefully that’s resolved soon and then I’ll see what can be done about this.

**Comment by dinan5** [comment]
or if you tell me what to look for I can help.  Im a retired CIO.

**Comment by dinan5** [comment]
Ok will take a look tonight. Thanks

On Jul 26, 2023, at 11:52, Brian Rogers ***@***.***> wrote:

﻿

Basically if you reference the code here, we are looking to find which property reflects motion detection on the camera. There are probably different ways of accomplishing it, my lazy way has been using breakpoints as we poll the data and see what changes when I toggle the switch in the app.

https://github.com/SecKatie/wyzeapy/blob/3dac073d5ae62adf58fe32226bd9a45aa779b88e/src/wyzeapy/types.py#L91
