### ISSUE TITLE
[Bug] Older wyze bulbs fail to load - Error while setting up wyzeapi platform for light

### ISSUE THREAD

**Issue by BoredMind** [SecKatie/ha-wyzeapi#504]
**Describe the bug**
Non color Wyze bulbs, pre-2019 bulbs, do not load any longer.    Started a few days ago.

**To Reproduce**

1. Go to Integrations -> Wyze Home Assistant Integration -> Entities
2. Click on any older, non color, Wyze bulb.
3. See error:

This entity is no longer being provided by the wyzeapi integration. If the entity is no longer in use, delete it in settings.

**Expected behavior**
Should be able to control bulb, cannot change any attributes. 

**System configuration**
HA Version: 2023.8.
WyzeApi Version: 0.1.22

**Device info**
WLPA19
by WyzeLabs

**home-assistant.log**

```
Error adding entities for domain light with platform wyzeapi
Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 996, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 822, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
```

**Comment by SecKatie** [comment]
@brg468 can you look at this issue? Is it related to your recent PR?

**Comment by brg468** [comment]
@SecKatie it must be based on the timing. I was under the impression that all bulbs reported the color mode property, but apparently the early ones might not. I’ll take a look.

**Comment by brg468** [comment]
@BoredMind if you would like to try this before it gets merged to make sure it actually fixes the problem, you can edit your light.py file starting at line 219 like below.

https://github.com/SecKatie/ha-wyzeapi/blob/c19080c2b2a5e8e4346c11faa567d32ed7fe9d28/custom_components/wyzeapi/light.py#L219-L223

**Comment by BoredMind** [comment]
The bulbs are now active again, and while I can turn them on and off, I get this error when it happens:


```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/wyzeapi/light.py:221
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:09:28 PM (3 occurrences)
Last logged: 4:09:38 PM

[547493361856] 'Bulb' object has no attribute 'color_mode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 201, in async_turn_on
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 903, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 996, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 822, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    if self._bulb.type is DeviceTypes.LIGHT:
                                 ^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
```

**Comment by BoredMind** [comment]
Did a full restart of HA, might not be seeing that error any longer, the "AttributeError: 'Bulb' object has no attribute 'color_mode'" one

**Comment by brg468** [comment]
So all good?

**Comment by BoredMind** [comment]
> So all good?

Appears to be all good

**Comment by saicrazyfire** [comment]
> @BoredMind if you would like to try this before it gets merged to make sure it actually fixes the problem, you can edit your light.py file starting at line 219 like below.
> 
> https://github.com/SecKatie/ha-wyzeapi/blob/c19080c2b2a5e8e4346c11faa567d32ed7fe9d28/custom_components/wyzeapi/light.py#L219-L223

I can confirm this works for me after a restart

**Comment by 1h8fulkat** [comment]
I am running 0.1.22 and verified that the modified code block exists in my light.py and I am still getting errors for my bulbs:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/wyzeapi/light.py:221
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:28:26 AM (18 occurrences)
Last logged: 11:11:15 AM

[139779071448256] 'Bulb' object has no attribute 'color_mode'
[139778598345024] 'Bulb' object has no attribute 'color_mode'
[139778603000000] 'Bulb' object has no attribute 'color_mode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 201, in async_turn_on
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 903, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 996, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 822, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'`

**Comment by brg468** [comment]
@1h8fulkat you modified the code as above? 0.1.22 does not incorporate this change unless you made it yourself.

**Comment by 1h8fulkat** [comment]
> @1h8fulkat you modified the code as above? 0.1.22 does not incorporate this change unless you made it yourself.

I retract my previous statement 🤦‍♂️

**Comment by prnewman** [comment]
Updating light.py fixed it for me

**Comment by RobertL1988** [comment]
Just completed the change and restarted HA. No more error.

**Comment by MMachor** [comment]
Just ran into this issue, or at least realized I was running into this issue.  Found the open bug with workaround and am happy to report that after adjusting the code it fixed the issue here as well.  Thank you!

**Comment by brg468** [comment]
@nicksardo, while I would like to see this get merged at well, let’s remember that this integration is totally built and maintained by volunteers in their spare time. Until the update is pushed, I gave you a simple copy and paste fix that you can choose to use or not.

**Comment by nibeckd** [comment]
This is my first attempt to edit code.  I applied the above and it worked for the first 3 of my 7 bulbs.  The other 4 are still showing Unavailable status.  Any advice?

**Comment by James62370** [comment]
I'm getting the same error with older 2019 Wyze bulbs.  I tried applying the fix above, but then most of my other bulbs don't even load.  The light turns on even with the error, but when ran within an automation, the script halts with an error and never completes the automation.

**Comment by James62370** [comment]
> @James62370 I'm guessing something didn't go right when you edited the code since the error still refers to the "if" statement on line 221. I posted an easier way to correct this problem here:
> 
> [#521 (comment)](https://github.com/SecKatie/ha-wyzeapi/issues/521#issuecomment-1757428836)

Thanks for pointing me to the right location.  I downloaded the updated script and appears to be working well now.
