### ISSUE TITLE
[Bug] 'Bulb' object has no attribute 'color_mode'

### ISSUE THREAD

**Issue by nstringham** [SecKatie/ha-wyzeapi#521]
**Describe the bug**
When I try to do anything it says `'Bulb' object has no attribute 'color_mode'`

**To Reproduce**

1. Set up Wyze bulb (2019)
2. install wyzeapi
3. connect to Wyze account
4. Attempt to turn bulb on or off or set color or brightness
5. Bulb does the right thing but home assistant UI gives error and doesn't update state of bulb

**Expected behavior**

no error appears and bulbs state updates corrctly

**System configuration**
System: HASSIO raspberry pi 4
Home Assistant: 2023.10.1
Supervisor: 2023.10.0
Operating System: 10.5
WyzeApi: 0.1.22

**home-assistant.log**

```
2023-10-06 22:35:05.014 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-06 22:35:05.016 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-06 22:35:19.866 WARNING (MainThread) [homeassistant.components.history] The 'exclude' option near /config/configuration.yaml:116 is deprecated, please remove it from your configuration
2023-10-06 22:35:20.469 DEBUG (MainThread) [custom_components.wyzeapi] Nothing to import from configuration.yaml, loading from Integrations
2023-10-06 22:35:28.265 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2023-10-06 22:35:28.267 DEBUG (MainThread) [custom_components.wyzeapi.sensor] Creating new WyzeApi sensor component
2023-10-06 22:35:28.321 DEBUG (MainThread) [custom_components.wyzeapi.lock] Creating new WyzeApi lock component
2023-10-06 22:35:28.322 DEBUG (MainThread) [custom_components.wyzeapi.climate] Creating new WyzeApi thermostat component
2023-10-06 22:35:28.322 DEBUG (MainThread) [custom_components.wyzeapi.siren] Creating new WyzeApi siren component
2023-10-06 22:35:28.325 DEBUG (MainThread) [custom_components.wyzeapi.alarm_control_panel] Creating new WyzeApi Home Monitoring System component
2023-10-06 22:35:28.378 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi light component
2023-10-06 22:35:29.333 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:35:29.361 ERROR (MainThread) [homeassistant.components.light] Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:35:29.738 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:35:31.534 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:35:33.676 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 403
2023-10-06 22:35:50.884 WARNING (SyncWorker_2) [homeassistant.components.google_wifi.sensor] Unable to fetch data from Google Wifi
2023-10-06 22:36:02.489 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:36:03.942 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:36:20.891 WARNING (SyncWorker_7) [homeassistant.components.google_wifi.sensor] Unable to fetch data from Google Wifi
2023-10-06 22:36:20.938 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 403
2023-10-06 22:36:34.411 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
2023-10-06 22:36:35.774 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/light.py", line 353, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1007, in state_attributes
    color_mode = self._light_internal_color_mode
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 833, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/light.py", line 221, in color_mode
    return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bulb' object has no attribute 'color_mode'
```

**Comment by nstringham** [comment]
My bulbs also say they are unavailable sometimes

**Comment by brg468** [comment]
See the comment [Here](https://github.com/SecKatie/ha-wyzeapi/issues/504#issuecomment-1666969629) for a workaround for now.

**Comment by talormanda** [comment]
I get something similar when I talk to my v1 wyze white bulbs. They are labled as WLPA19 on home assistant and when I try to turn them on I get: `Failed to call service light/turn_on. 'Bulb' object has no attribute 'color_mode'`.

My color bulbs work fine, however.

**Comment by geoffrothman** [comment]
this is an error with the main repo...in light.py change the line starting at 219 to read like this instead...save, restart HA:

    @property
    def color_mode(self):
         if self._bulb.type is DeviceTypes.LIGHT: 
         return ColorMode.COLOR_TEMP 
     return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS

**Comment by talormanda** [comment]
> this is an error with the main repo...in light.py change the line starting at 219 to read like this instead...save, restart HA:
> 
> ```
> @property
> def color_mode(self):
>      if self._bulb.type is DeviceTypes.LIGHT: 
>      return ColorMode.COLOR_TEMP 
>  return ColorMode.COLOR_TEMP if self._bulb.color_mode == "2" else ColorMode.HS 
> ```

When or what needs to happen to make this become part of the production build for everyone?

**Comment by brg468** [comment]
Another option which I haven’t tried is go to HACS, Wyze integration, upper right, redownload, and under the version select master. The change is in the master branch so that may be an easier way.

**Comment by digitaldawg1** [comment]
> Another option which I haven’t tried is go to HACS, Wyze integration, upper right, redownload, and under the version select master. The change is in the master branch so that may be an easier way.

Thanks.  I did this and it fixed the issue.

**Comment by zvarnes** [comment]
I'm experiencing the same issue. I tried redownloading the 'master' version, but I'm still getting the same errors. I even removed the wyze integration and reinstalled. 
![image](https://github.com/SecKatie/ha-wyzeapi/assets/39716849/5a0fcbb0-9080-4d61-973f-4861d637e92c)

**Comment by brg468** [comment]
@zvarnes I assume you restarted after redownloading? Maybe try deleting the wyzeapi folder from custom_compenents and then try redownloading from master.

**Comment by zvarnes** [comment]
Removed everything. Readded everything. Created new wyze api key. As soon as I added it, the errors started. (also the folder gets deleted when the integration is removed. at least for docker)

**Comment by brg468** [comment]
Can you see if the change indicated above is in your light.py file?

**Comment by zvarnes** [comment]
No it doesn't match on v1.22. I manually updated it to the code linked [here](https://github.com/SecKatie/ha-wyzeapi/blob/c19080c2b2a5e8e4346c11faa567d32ed7fe9d28/custom_components/wyzeapi/light.py#L219-L223) and it appears to be working now!

**Comment by omar10wahab** [comment]
> Another option which I haven’t tried is go to HACS, Wyze integration, upper right, redownload, and under the version select master. The change is in the master branch so that may be an easier way.

This solution worked for me. Sometimes my wyze bulbs would work but always with an error but switching to master build fixed the issue. Thanks

**Comment by whwar9739** [comment]
Can we get this change included in a new release?

**Comment by waytgibbs** [comment]
The code block in light.py at line 219 still needs to be pulled into master. Otherwise all HA scripts calling a WYZE bulb will fail with an error unless the light.py code is manually patched on the host system.

**Comment by zvarnes** [comment]
> The code block in light.py at line 219 still needs to be pulled into master. Otherwise all HA scripts calling a WYZE bulb will fail with an error unless the light.py code is manually patched on the host system.

It was pulled into master https://github.com/SecKatie/ha-wyzeapi/compare/0.1.21...0.1.22

**Comment by SecKatie** [comment]
@brg468 do we have a PR for this?

**Comment by brg468** [comment]
@SecKatie  it was merged a while ago but a new version was never published to HACS.

**Comment by zvarnes** [comment]
Don't we just manually add this repo into HACS? What merging needs to be done?

**Comment by SecKatie** [comment]
I have pushed a new version! Sorry for the delay!
