### ISSUE TITLE
[12/24/2023, 10:12:28 AM] [Wyze] Error: AccessTokenError     at WyzeAPI._performRequest (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:132:15)     at processTicksAndRejections (node:internal/process/task_queues:95:5)     at WyzeAPI.request (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:80:14)     at WyzeAPI.getObjectList (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:234:20)     at WyzeSmartHome.refreshDevices (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:101:26)     at WyzeSmartHome.runLoop (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:90:9) [12/24/2023, 10:12:28 AM] [Wyze] Error, refreshing access token and trying again

### ISSUE THREAD

**Issue by djjerryo** [SecKatie/ha-wyzeapi#535]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
This error is not related to this repo. Your error looks to be from the Wyze-homebridge integration. Please close and post there.

**Comment by djjerryo** [comment]
sorry, but I am new to this and still can't get it every Everything was working now it's not !!!! i will try to post in the right spot next time ..
