### ISSUE TITLE
[Bug] module misspelled? 

### ISSUE THREAD

**Issue by yankees5963** [SecKatie/ha-wyzeapi#549]
Home assistant updated and wyze integration no longer works. Says no. Module wyzeapy should it be wyzeapi? 

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 3:02:19 AM (1 occurrences)
Last logged: 3:02:19 AM

```
Setup failed for custom integration 'wyzeapi': Unable to import component: No module named 'wyzeapy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wyzeapi/__init__.py", line 13, in <module>
    from wyzeapy import Wyzeapy
ModuleNotFoundError: No module named 'wyzeapy' 
```

**Comment by brg468** [comment]
Wyzeapy is another library that the integration uses, it’s not a misspelling. Since the latest HA version switched to Python 3.12 maybe that library didn’t get installed in the right place. I’d try removing the Wyze integration from HA and HACS and reinstalling and see if that fixes it.

**Comment by christophermichaelshaw** [comment]
I too am having this issue on:
Core
2024.2.1
Supervisor
2024.02.0
Operating System
12.0.rc1
Frontend
20240207.1

Integration was previously working without issue prior to recent updates.

Here is the relevant error that should shed some light on the issue:
`Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 06:02:12 (1 occurrences)
Last logged: 06:02:12

Error setting up entry for wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/__init__.py", line 128, in async_setup_entry
    mac_addresses = await client.unique_device_ids
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/__init__.py", line 148, in unique_device_ids
    devices = await self._service.get_object_list()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/base_service.py", line 119, in get_object_list
    response_json = await self._auth_lib.post("https://api.wyzecam.com/app/v2/home_page/get_object_list",
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/wyze_auth_lib.py", line 248, in post
    response = await _session.post(url, json=json, headers=headers, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
asyncio.exceptions.CancelledError
`

More context here from the Python documentation: https://docs.python.org/3.12/whatsnew/3.12.html#ssl

Remove the ssl.wrap_socket() function, deprecated in Python 3.7: instead, create a ssl.SSLContext object and call its ssl.SSLContext.wrap_socket method. Any package that still uses ssl.wrap_socket() is broken and insecure. The function neither sends a SNI TLS extension nor validates server hostname. Code is subject to CWE-295: Improper Certificate Validation. (Contributed by Victor Stinner in https://github.com/home-assistant/core/issues/94199.)

See also: https://github.com/home-assistant/core/issues/109772#issuecomment-1944543646

**Comment by christophermichaelshaw** [comment]
Can confirm redownload/reinstall worked for me.
