### ISSUE TITLE
[Bug] PlugIn should wrap error to native HomeAssistant error to support 'continue_on_error'

### ISSUE THREAD

**Issue by Abba-** [SecKatie/ha-wyzeapi#559]
**Describe the bug**

Without being able to dive into the code, I'm making a bit of an assumption here.
I'm assuming that this plugin throws a generic error (vs a HomeAssistant specific error) when something isnt as expected.

HomeAssistant [continue_on_error](https://www.home-assistant.io/docs/scripts/#continuing-on-error) only handles HomeAsssistant specific errors.  [Sample discussion](https://community.home-assistant.io/t/continue-on-error-as-the-default/595231/13) and [2](https://community.home-assistant.io/t/continue-on-error-not-working/429947/8).

So if any error happens (which can be a separate report, I seem to sometime get an error even though an action was successful), currently the whole script stops instead of being able to be 'caught' by HomeAssistant and continuing.

Sample error:
```
2024-03-20 14:38:41.564 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140589164157248] {'code': '3005', 'ts': 1710959921516, 'msg': 'property only set by main user', 'data': {}, 'traceId': 'aae52bcd55cf61a9a334226aa00c2c6d'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wyzeapi/switch.py", line 334, in async_turn_on
    await self._service.turn_on_notifications(self._device)
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/camera_service.py", line 123, in turn_on_notifications
    await self._set_property(camera, PropertyIDs.NOTIFICATION.value, "1")
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/base_service.py", line 359, in _set_property
    check_for_errors_standard(response_json)
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/utils.py", line 84, in check_for_errors_standard
    raise UnknownApiError(response_json)
```

**### (There is currently workaround by calling scripts via script.turn_on)**

**Comment by neilbrookins** [comment]
I’ve run into this too.  It causes problems when the failure is minor and non fatal, and the automation then fails to run the next step in a sequence that may be a very critical important step.  So, I’m agreeing this is an important improvement.

**Comment by Abba-** [comment]
Voting for this to be kept open...

**Comment by Abba-** [comment]
Can we unstale ?

**Comment by brg468** [comment]
I’ll reopen, it would be a nice improvement. Can’t say anyone will get to it anytime soon but it’s worth keeping as a a feature request/enhancement IMHO.

**Comment by kaovilai** [comment]
unstale

**Comment by Abba-** [comment]
Stayin Alive stayin alive

**Comment by chuckmdonaldson** [comment]
@SecKatie can we get this issue addressed?

**Comment by SecKatie** [comment]
It shouldn't close now that it has the correct tag

**Comment by brg468** [comment]
Changing tag to enhancement to avoid the stale-bot.
