### ISSUE TITLE
[Bug] Thermostat no longer being provided by the wyzeapi integration

### ISSUE THREAD

**Issue by Jkweks** [SecKatie/ha-wyzeapi#586]
Recently updated HA to the most recent distro, updated the Wyze integration through HACS, now all the devices and entities load, except for my Wyze Thermostat, multiple resets of the devices, the HA system and resetting the login credentials yield the same result. The strange part that I'm seeing is that if I open up the device info on HA, the MAC address listed is: CO_EA1_523248370F3539374B45588C, not 2C:AA:8E:C9:A0:44.

Update HA
Update Wyze Integration through HACS
Setup Login
Devices and Entities form, including Thermostat, just no data retrieved

**Expected behavior**
Start HA, have control of thermostat through HACS integration

**System configuration**
System: RPI 4, Docker, wired Internet connection
HA Version: 2024.5.4
WyzeApi Version: 0.1.24

2024-05-20 22:32:30.038 ERROR (MainThread) [wyzeapy.services.update_manager] Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/update_manager.py", line 44, in update
    self.device.callback_function(self.device)
  File "/config/custom_components/wyzeapi/climate.py", line 316, in async_update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 460, in state
    return HVACMode(hvac_mode).value  # type: ignore[unreachable]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: <HVACMode.OFF: 'off'> is not a valid HVACMode
```

**Comment by SecKatie** [comment]
Can you check the latest release? It should include the fix for this.

**Comment by Jkweks** [comment]
Going to close this  issue. The latest update fixed it. Thank you much!
