### ISSUE TITLE
[Bug] <short description of issue>Get an "unknown error"

### ISSUE THREAD

**Issue by justinm80** [SecKatie/ha-wyzeapi#635]
**Describe the bug**
 I am trying to setup app. I click on devices and add integration. I type in my Wyze login information and copy and paste the Api id and key. I click submit and at the top of the window I see "Unknown Error". It does not matter which version of the Wyze software I install. the Wyze app does not work.

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
Check the logs. Most likely you entered one of the credentials incorrectly.

**Comment by justinm80** [comment]
This is the error I see from the log

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: October 6, 2024 at 4:53:14 PM (2 occurrences)
Last logged: 5:21:23 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/config_flow.py", line 61, in async_step_user
    await self.client.login(
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/__init__.py", line 89, in login
    await self._auth_lib.get_token_with_username_password(
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/wyze_auth_lib.py", line 144, in get_token_with_username_password
    raise AccessTokenError
wyzeapy.exceptions.AccessTokenError

**Comment by brg468** [comment]
Is there another error from Wyze? Still looks like a credential error to me.

**Comment by grainsoflight** [comment]
I am experiencing this as well, my api token expired and when I went to enter the new one, I get the unknown error. Created a new key several times, didn't fix it. Even changed my password on wyze and tried the new credentials, still didn't work, unable to reconfigure the integration

**Comment by grainsoflight** [comment]
This is what I see in my logs 
![Screenshot_20241016_001106_Home Assistant](https://github.com/user-attachments/assets/f73b0d53-b46a-4b40-98d7-0eafe7193faa)
![Screenshot_20241016_001034_Home Assistant](https://github.com/user-attachments/assets/673846e6-f24e-4121-9178-5dd3e9f314a4)

**Comment by brg468** [comment]
That looks like something is wrong with your installs from HACS. Try redownloading Wyze through HACS and see if that fixes it.

**Comment by grainsoflight** [comment]
> That looks like something is wrong with your installs from HACS. Try redownloading Wyze through HACS and see if that fixes it.

I removed from HACS but now when I go to redownload I get this message "The version for this integration can not be used with HACS."

**Comment by grainsoflight** [comment]
Was able to resolve the previous issues with a reboot of the machine, but once I could finally reauthenticate, the lightbulbs loaded with no entities

**Comment by brg468** [comment]
No response from the OP, closing.
